export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";
export const UPDATE_ORDER_LIST = "UPDATE_ORDER_LIST";
export const UPDATE_CHAT = "UPDATE_CHAT";
